/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as ContactLazyV18RouteImport } from './routes/contact.lazy.v-18'

const PastLazyRouteImport = createFileRoute('/past')()
const OrderLazyRouteImport = createFileRoute('/order')()
const ContactLazyRouteImport = createFileRoute('/contact')()
const IndexLazyRouteImport = createFileRoute('/')()

const PastLazyRoute = PastLazyRouteImport.update({
  id: '/past',
  path: '/past',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/past.lazy').then((d) => d.Route))
const OrderLazyRoute = OrderLazyRouteImport.update({
  id: '/order',
  path: '/order',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/order.lazy').then((d) => d.Route))
const ContactLazyRoute = ContactLazyRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/contact.lazy').then((d) => d.Route))
const IndexLazyRoute = IndexLazyRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))
const ContactLazyV18Route = ContactLazyV18RouteImport.update({
  id: '/lazy/v-18',
  path: '/lazy/v-18',
  getParentRoute: () => ContactLazyRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexLazyRoute
  '/contact': typeof ContactLazyRouteWithChildren
  '/order': typeof OrderLazyRoute
  '/past': typeof PastLazyRoute
  '/contact/lazy/v-18': typeof ContactLazyV18Route
}
export interface FileRoutesByTo {
  '/': typeof IndexLazyRoute
  '/contact': typeof ContactLazyRouteWithChildren
  '/order': typeof OrderLazyRoute
  '/past': typeof PastLazyRoute
  '/contact/lazy/v-18': typeof ContactLazyV18Route
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexLazyRoute
  '/contact': typeof ContactLazyRouteWithChildren
  '/order': typeof OrderLazyRoute
  '/past': typeof PastLazyRoute
  '/contact/lazy/v-18': typeof ContactLazyV18Route
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/contact' | '/order' | '/past' | '/contact/lazy/v-18'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/contact' | '/order' | '/past' | '/contact/lazy/v-18'
  id: '__root__' | '/' | '/contact' | '/order' | '/past' | '/contact/lazy/v-18'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexLazyRoute: typeof IndexLazyRoute
  ContactLazyRoute: typeof ContactLazyRouteWithChildren
  OrderLazyRoute: typeof OrderLazyRoute
  PastLazyRoute: typeof PastLazyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/past': {
      id: '/past'
      path: '/past'
      fullPath: '/past'
      preLoaderRoute: typeof PastLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/order': {
      id: '/order'
      path: '/order'
      fullPath: '/order'
      preLoaderRoute: typeof OrderLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact/lazy/v-18': {
      id: '/contact/lazy/v-18'
      path: '/lazy/v-18'
      fullPath: '/contact/lazy/v-18'
      preLoaderRoute: typeof ContactLazyV18RouteImport
      parentRoute: typeof ContactLazyRoute
    }
  }
}

interface ContactLazyRouteChildren {
  ContactLazyV18Route: typeof ContactLazyV18Route
}

const ContactLazyRouteChildren: ContactLazyRouteChildren = {
  ContactLazyV18Route: ContactLazyV18Route,
}

const ContactLazyRouteWithChildren = ContactLazyRoute._addFileChildren(
  ContactLazyRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexLazyRoute: IndexLazyRoute,
  ContactLazyRoute: ContactLazyRouteWithChildren,
  OrderLazyRoute: OrderLazyRoute,
  PastLazyRoute: PastLazyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
